/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authConfirmRouteImport } from './routes/(auth)/confirm'
import { Route as appTeamIdRouteRouteImport } from './routes/(app)/$teamId/route'
import { Route as appTeamIdSettingsRouteImport } from './routes/(app)/$teamId/settings'
import { Route as appTeamIdSectionRouteImport } from './routes/(app)/$teamId/$section'
import { Route as appTeamIdInvoicesIndexRouteImport } from './routes/(app)/$teamId/invoices/index'
import { Route as appTeamIdInvoicesInvoiceIdRouteImport } from './routes/(app)/$teamId/invoices/$invoiceId'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authConfirmRoute = authConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => authRouteRoute,
} as any)
const appTeamIdRouteRoute = appTeamIdRouteRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => appRouteRoute,
} as any)
const appTeamIdSettingsRoute = appTeamIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appTeamIdRouteRoute,
} as any)
const appTeamIdSectionRoute = appTeamIdSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => appTeamIdRouteRoute,
} as any)
const appTeamIdInvoicesIndexRoute = appTeamIdInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => appTeamIdRouteRoute,
} as any)
const appTeamIdInvoicesInvoiceIdRoute =
  appTeamIdInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => appTeamIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$teamId': typeof appTeamIdRouteRouteWithChildren
  '/confirm': typeof authConfirmRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/$teamId/$section': typeof appTeamIdSectionRoute
  '/$teamId/settings': typeof appTeamIdSettingsRoute
  '/$teamId/invoices/$invoiceId': typeof appTeamIdInvoicesInvoiceIdRoute
  '/$teamId/invoices/': typeof appTeamIdInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/$teamId': typeof appTeamIdRouteRouteWithChildren
  '/confirm': typeof authConfirmRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
  '/$teamId/$section': typeof appTeamIdSectionRoute
  '/$teamId/settings': typeof appTeamIdSettingsRoute
  '/$teamId/invoices/$invoiceId': typeof appTeamIdInvoicesInvoiceIdRoute
  '/$teamId/invoices': typeof appTeamIdInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/$teamId': typeof appTeamIdRouteRouteWithChildren
  '/(auth)/confirm': typeof authConfirmRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/$teamId/$section': typeof appTeamIdSectionRoute
  '/(app)/$teamId/settings': typeof appTeamIdSettingsRoute
  '/(app)/$teamId/invoices/$invoiceId': typeof appTeamIdInvoicesInvoiceIdRoute
  '/(app)/$teamId/invoices/': typeof appTeamIdInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$teamId'
    | '/confirm'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/$teamId/$section'
    | '/$teamId/settings'
    | '/$teamId/invoices/$invoiceId'
    | '/$teamId/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$teamId'
    | '/confirm'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/'
    | '/$teamId/$section'
    | '/$teamId/settings'
    | '/$teamId/invoices/$invoiceId'
    | '/$teamId/invoices'
  id:
    | '__root__'
    | '/(app)'
    | '/(auth)'
    | '/(app)/$teamId'
    | '/(auth)/confirm'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(app)/'
    | '/(app)/$teamId/$section'
    | '/(app)/$teamId/settings'
    | '/(app)/$teamId/invoices/$invoiceId'
    | '/(app)/$teamId/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/confirm': {
      id: '/(auth)/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof authConfirmRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/$teamId': {
      id: '/(app)/$teamId'
      path: '/$teamId'
      fullPath: '/$teamId'
      preLoaderRoute: typeof appTeamIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/$teamId/settings': {
      id: '/(app)/$teamId/settings'
      path: '/settings'
      fullPath: '/$teamId/settings'
      preLoaderRoute: typeof appTeamIdSettingsRouteImport
      parentRoute: typeof appTeamIdRouteRoute
    }
    '/(app)/$teamId/$section': {
      id: '/(app)/$teamId/$section'
      path: '/$section'
      fullPath: '/$teamId/$section'
      preLoaderRoute: typeof appTeamIdSectionRouteImport
      parentRoute: typeof appTeamIdRouteRoute
    }
    '/(app)/$teamId/invoices/': {
      id: '/(app)/$teamId/invoices/'
      path: '/invoices'
      fullPath: '/$teamId/invoices/'
      preLoaderRoute: typeof appTeamIdInvoicesIndexRouteImport
      parentRoute: typeof appTeamIdRouteRoute
    }
    '/(app)/$teamId/invoices/$invoiceId': {
      id: '/(app)/$teamId/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/$teamId/invoices/$invoiceId'
      preLoaderRoute: typeof appTeamIdInvoicesInvoiceIdRouteImport
      parentRoute: typeof appTeamIdRouteRoute
    }
  }
}

interface appTeamIdRouteRouteChildren {
  appTeamIdSectionRoute: typeof appTeamIdSectionRoute
  appTeamIdSettingsRoute: typeof appTeamIdSettingsRoute
  appTeamIdInvoicesInvoiceIdRoute: typeof appTeamIdInvoicesInvoiceIdRoute
  appTeamIdInvoicesIndexRoute: typeof appTeamIdInvoicesIndexRoute
}

const appTeamIdRouteRouteChildren: appTeamIdRouteRouteChildren = {
  appTeamIdSectionRoute: appTeamIdSectionRoute,
  appTeamIdSettingsRoute: appTeamIdSettingsRoute,
  appTeamIdInvoicesInvoiceIdRoute: appTeamIdInvoicesInvoiceIdRoute,
  appTeamIdInvoicesIndexRoute: appTeamIdInvoicesIndexRoute,
}

const appTeamIdRouteRouteWithChildren = appTeamIdRouteRoute._addFileChildren(
  appTeamIdRouteRouteChildren,
)

interface appRouteRouteChildren {
  appTeamIdRouteRoute: typeof appTeamIdRouteRouteWithChildren
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appTeamIdRouteRoute: appTeamIdRouteRouteWithChildren,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authConfirmRoute: typeof authConfirmRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authConfirmRoute: authConfirmRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
